name: mp_chart
description: A Flutter chart package just like AndroidMPChart, apply easy to use chart for Flutter.
version: 0.3.1
author: SunPointed<410338643@qq.com>
homepage: https://github.com/SunPointed/MPFlutterChart
publish_to: none

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  path_drawing: ^0.5.0-nullsafety.0
  optimized_gesture_detector:
    git:
      url: git@github.com:datdescartes/OptimizedGestureDetector.git
      ref: master
  #  vector_math: ^2.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

